server:
  port: 8090
fastlog:
  enable: true
  url: 192.168.166.7:9092
  topic: log4
  #url: pulsar://localhost:6650
  #topic: persistent://log/test1/test-topic
  batchMessageSize: 2048
  mqType: kafka
  partition: 4
  async: true
  fileMemoryCacheSize: 8
  fileMaxCacheCount: 64
